name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Copy files to GCP
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: ./
        remote_path: /path/to/your/app
        remote_host: ${{ secrets.GCP_SSH_HOST }}
        remote_port: ${{ secrets.GCP_SSH_PORT }}
        remote_user: ${{ secrets.GCP_SSH_USER }}
        remote_key: ${{ secrets.GCP_SSH_KEY }}

    - name: SSH and restart services
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.GCP_SSH_HOST }}
        username: ${{ secrets.GCP_SSH_USER }}
        key: ${{ secrets.GCP_SSH_KEY }}
        port: ${{ secrets.GCP_SSH_PORT }}
        script: |
          cd /path/to/your/app
          source venv/bin/activate
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx